User_name = input("What is your name? ")
User_age = input("How old are you? ")
User_liveplace = input("Where are you live? ")
print ( "This is", User_name)
print ( "It is" , User_age)
print ( "(S)he live in", User_liveplace)